[package]
name = "unl3d-pricer"
version = "1.14.3"
description = "Calculateur de prix d'impression 3D"
authors = ["Amélien LARADE"]
edition = "2021"

[lib]
name = "unl3d_prix_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
